FROM --platform=$BUILDPLATFORM python:3.10-alpine

WORKDIR /src
COPY requirements.txt /src
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . .

CMD ["python3", "app.py"]
